modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP/issues"

[[mods]]
modId = "palordersmp"
version="${file.jarVersion}"
displayName="PalorderSMP"
displayURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP"
logoFile="LongLiveTheEmpire.png"
credits="Thanks to Forge for making this mod possible."
authors="Main Programmer: Maneewan Van Breugel; Special Thanks: MichaÃ«l van de Giessen aka tubbynl"
description='''Palorder SMP Server Mod.
A project by a beginner programmer that adds a fucking nuke.
'''

[[dependencies.palordersmp]]
modId="forge"
mandatory=true
versionRange="[40.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.palordersmp]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1)"
ordering="NONE"
side="BOTH"
