modLoader="javafml"
loaderVersion="[47,)"  # Accepts any loader version 47 or higher
license="All rights reserved"
issueTrackerURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP/issues"

[[mods]]
modId="palordersmp_tweaked"
version="4.5"
displayName="PalorderSMP tweaked"
displayURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP"
logoFile="LongLiveTheEmpire.png"
credits="Created by PalorderSoftWorksOfficial"
authors="PalorderSoftWorksOfficial,SquidDev"
description='''
PalorderSMP-Tweaked is a powerful server-side modification created by PalorderSoftWorksOfficial.
It enhances server management and gameplay features while maintaining full compatibility with Minecraft 1.20.1.
Future updates will include integration with popular mods like ComputerCraft to expand automation and scripting capabilities.
Designed for stability, performance, and ease of use, this mod is ideal for both small and large server environments.
'''
dependencies = [
    { modId="forge", mandatory=true, versionRange="[47,)", side="BOTH" },
    { modId="minecraft", mandatory=true, versionRange="[1.20.1,)", side="BOTH" },
    { modId="computercraft", mandatory=false, versionRange="[1.113.1,)", ordering="AFTER", side="BOTH" },
    { modId="kotlinforforge", mandatory=false, versionRange="[4.3.0,)", side="BOTH" }
]
[[mods]]
modId="palordersmp_tweaked_kotlin_beta"
version="1.7-4.5"
displayName="PalorderSMP tweaked kotlin beta"
displayURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP"
logoFile="LongLiveTheEmpire.png"
credits="Created by PalorderSoftWorksOfficial"
authors="PalorderSoftWorksOfficial,SquidDev"
description='''
This is a kotlin beta build of that requires kotlin for forge!
These builds are mostly unstable as these are included in the main jar for compatibiltity
'''
dependencies = [
    { modId="forge", mandatory=true, versionRange="[47,)", side="BOTH" },
    { modId="minecraft", mandatory=true, versionRange="[1.20.1,)", side="BOTH" },
    { modId="kotlinforforge", mandatory=true, versionRange="[4.3.0,)", side="BOTH" },
    { modId="computercraft", mandatory=false, versionRange="[1.113.1)", side="BOTH"}
]