modLoader="javafml"
loaderVersion="[47,)"  # Accepts any loader version 47 or higher
license="All rights reserved"
issueTrackerURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP/issues"

[[mods]]
modId="palordersmp_tweaked"
version="3.2"
displayName="PalorderSMP tweaked"
displayURL="https://github.com/PalorderSoftworksOfficial/PalorderSMP"
logoFile="LongLiveTheEmpire.png"
credits="Created by PalorderSoftWorksOfficial"
authors="PalorderSoftWorksOfficial,SquidDev"
description='''
PalorderSMP-Tweaked is a powerful server-side modification created by PalorderSoftWorksOfficial.
It enhances server management and gameplay features while maintaining full compatibility with Minecraft 1.20.1.
Future updates will include integration with popular mods like ComputerCraft to expand automation and scripting capabilities.
Designed for stability, performance, and ease of use, this mod is ideal for both small and large server environments.
'''

[[dependencies.palordersmp_tweaked]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.palordersmp_tweaked]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.palordersmp_tweaked]]
modId="computercraft"
mandatory=false
versionRange="[1.113.1,)"
ordering="AFTER"
side="BOTH"
[[dependencies.palordersmp_tweaked]]
modId="kotlinforforge"
mandatory=false
versionRange="[4.3.0,)"
ordering="NONE"
side="BOTH"